<?php
/**
 * @file
 * optimhealth_work_comp.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function optimhealth_work_comp_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-work_comp-field_work_comp_body'.
  $field_instances['node-work_comp-field_work_comp_body'] = array(
    'bundle' => 'work_comp',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_work_comp_body',
    'label' => 'Body',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');

  return $field_instances;
}
